### PR TITLE
Quiz bug fix

### LINKED ISSUE #3: Code reformat: Quiz component
User Responses are not being updated

### LINKED ISSUE #4: DB Query Fix: Question component
Questions must be pulled from the DB

### PR DESCRIPTION
**Pull request by vkoli**
1. Fixed the User Responses state, so now the state should be updated when you click an answer
2. Added query from db from questions  
3. Reformatted the code and took out most console logs/comments

### CODE REVIEW

File: src/components/Quiz.js [hunk 1]
```diff
@@ -3,9 +3,17 @@ import Question from './Question.js'
 import Socket from './Socket.js'
 import Button from '@material-ui/core/Button'
 import { gql, useQuery, useMutation } from '@apollo/client'
-//import { GET_ALL_QUESTIONS } from "../graphql/queries";
 import {List,ListItem,Paper,Card} from '@material-ui/core'
 
+const queryString = `
```
Comment (ammist07) [inline src/components/Quiz.js]: Move the Queries to the queries file and export it here

**Review by ammist07 — CHANGES_REQUESTED** [review]

**Review by rpasricha45 — APPROVED** [review]
if you could make the height less tall /and less wide , but not a big deal
